import json
from pathlib import Path
import sys
import tempfile
import unittest

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "code"))
from verify_release_integrity import create, verify


class ReleaseIntegrityTests(unittest.TestCase):
    def setUp(self):
        self.directory = tempfile.TemporaryDirectory()
        self.addCleanup(self.directory.cleanup)
        self.root = Path(self.directory.name)
        (self.root / "example.txt").write_text("example\n", encoding="ascii")
        create(self.root)

    def test_round_trip(self):
        self.assertEqual(verify(self.root)["files"], 1)

    def test_modified_file(self):
        (self.root / "example.txt").write_text("changed\n", encoding="ascii")
        with self.assertRaises(ValueError):
            verify(self.root)

    def test_missing_file(self):
        (self.root / "example.txt").unlink()
        with self.assertRaises(ValueError):
            verify(self.root)

    def test_extra_files_are_explicit(self):
        (self.root / "generated.txt").write_text("local result\n", encoding="ascii")
        with self.assertRaises(ValueError):
            verify(self.root)
        self.assertEqual(verify(self.root, allow_extra=True)["extra_files"], 1)

    def test_bytecode_must_not_be_published(self):
        cache = self.root / "__pycache__"
        cache.mkdir()
        (cache / "example.pyc").write_bytes(b"generated bytecode")
        with self.assertRaises(ValueError):
            create(self.root)

    def test_path_and_duplicate_rejection(self):
        path = self.root / "MANIFEST.json"
        original = path.read_bytes()
        for name in ("../example.txt", "/example.txt", "C:/example.txt", "./example.txt", "a\\b"):
            data = json.loads(original)
            data["files"][0]["path"] = name
            path.write_text(json.dumps(data), encoding="ascii")
            with self.assertRaises(ValueError):
                verify(self.root)
        data = json.loads(original)
        data["files"].append(data["files"][0])
        path.write_text(json.dumps(data), encoding="ascii")
        with self.assertRaises(ValueError):
            verify(self.root)


if __name__ == "__main__":
    unittest.main()
