#pragma once

#include "utsp/native_core.hpp"

#include <cstdint>
#include <span>
#include <vector>

namespace utsp {

struct LabelSpaceAutomorphism {
  std::vector<std::uint32_t> ambient_basis_images;
  std::vector<Mask> quotient_basis_images;
};

struct SupportAutomorphismSubgroup {
  std::uint32_t ambient_dimension = 0;
  std::uint32_t quotient_dimension = 0;
  std::uint32_t elementary_generator_count = 0;
  std::uint64_t subgroup_order = 1;
  std::vector<LabelSpaceAutomorphism> generators;
};

struct QuotientVectorOrbit {
  Mask representative = 0;
  std::uint64_t size = 0;
};

struct IsotropicOrbitCoverSummary {
  std::uint64_t vector_orbits = 0;
  std::uint64_t candidate_subspaces = 0;
};

// Return the subgroup generated by all coordinate swaps and transvections
// that preserve the pointed support exactly. Every returned ambient map and
// induced quotient map is invertible.
[[nodiscard]] SupportAutomorphismSubgroup elementary_support_automorphisms(
    const LabelSpace& label_space);

[[nodiscard]] Mask apply_quotient_automorphism(
    Mask vector, std::span<const Mask> basis_images);

[[nodiscard]] std::vector<QuotientVectorOrbit> quotient_vector_orbits(
    const SupportAutomorphismSubgroup& subgroup);

[[nodiscard]] IsotropicOrbitCoverSummary enumerate_isotropic_orbit_cover(
    const LabelSpace& label_space,
    std::uint32_t dimension,
    const SupportAutomorphismSubgroup& subgroup,
    std::uint32_t orbit_depth = 1,
    const IsotropicVisitor& visitor = {});

}  // namespace utsp
